### ISSUE TITLE
make_far2l_deb.sh on ubuntu 22.04 / arm64

### ISSUE THREAD

**Issue by ecc256** [unxed/far2l-deb#1]
I’ve run make_far2l_deb.sh just now on ubuntu 22.04 / arm64

Minor issues to report:

1.
_E: Package 'libwxgtk3.0-dev' has no installation candidate_

2.
2nd “mkdir deb/far2l/usr/share”:
_mkdir: cannot create directory ‘deb/far2l/usr/share’: File exists_

3.
**sudo apt install ./far2l_arm64.deb**
_N: Download is performed unsandboxed as root as file '/home/ubuntu/far2l_arm64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)_

**Far2l** get installed and I’m able to run it, tho!
Anything to check or to be worried about?

Thanks!

**Comment by Arkady23** [comment]
Где взять deb-пакет для последнего чистого дебиана? Ядро как в последнем Ubuntu 22.10.1, т.е. 5.19.0.2. То что находится у Павла в ppa дает ошибку установки пакета в связи с фэйсбучной упаковкой tar.zst.

**Comment by ecc256** [comment]
Надо самому делать, где-то тут был make_far2l_deb.sh...

**Comment by unxed** [comment]
>  Anything to check or to be worried about?

These are minor issues, you can safely ignore them!
