### ISSUE TITLE
NetRocks - FTP get error 'stat failed (2)'

### ISSUE THREAD

**Issue by simonovich** [unxed/far2l-deb#16]
I don't upload files on my FTP server, error 'stat failed (2)'.
The error is repeated for upload from zip and tar.gz
By example:
https://www.drupal.org/project/drupal/releases/8.8.5

See my screencast:
https://youtu.be/zZaU8XL4meY

My FAR version from https://launchpad.net/~far2l-team/+archive/ubuntu/ppa
Ubuntu 18.04

**Comment by unxed** [comment]
I do not maintain whose ppa. You should open an issue in https://github.com/elfmz/far2l instead.
