### ISSUE TITLE
how to access far:config?

### ISSUE THREAD

**Issue by nomoglow** [unxed/far2l-deb#17]
just asking

**Comment by unxed** [comment]
see ~/.config/far2l

**Comment by nomoglow** [comment]
ok, i guess then that System.MsWheelDelta aint accessible yet. please keep in mind that 3 line scroll in editor more convenient than 1)

**Comment by unxed** [comment]
> ok, i guess then that System.MsWheelDelta aint accessible yet. please keep in mind that 3 line scroll in editor more convenient than 1)

you'd better to file a ticket to here https://github.com/elfmz/far2l/issues about this
