### ISSUE TITLE
ubuntu 20 min install - fakeroot: команда не найдена

### ISSUE THREAD

**Issue by daemonserj** [unxed/far2l-deb#18]
mkdir: невозможно создать каталог «deb/far2l/usr/share»: Файл существует
./make_far2l_deb.sh: строка 80: fakeroot: команда не найдена
cp: не удалось выполнить stat для 'far2l.deb': Нет такого файла или каталога
mv: не удалось выполнить stat для 'far2l.deb': Нет такого файла или каталога
daemonserj@samsbar:~/TEMP/far2l-deb-master$ fakeroot

**Comment by akruphi** [comment]
В **make_far2l_deb.sh** стоит добавить строку
`sudo apt install -y fakeroot # need for build deb in step 3`
иначе действительно возникает такая проблема.
