### ISSUE TITLE
network is down inside lxc

### ISSUE THREAD

**Issue by sorcodiv** [unxed/far2l-deb#2]
Здравствуйте!
При сборке portable-версии в debian 11 столкнулся с проблемой: после создания lxc-контейнера сеть не поднимается автоматически.
Мне помогло добавление в скрипт lxc-far2l-portable.sh двух строк:
sudo lxc-attach -n far2l -- dhclient eth0
echo nameserver 1.1.1.1 | sudo lxc-attach -n far2l -- tee /run/resolvconf/resolv.conf

И в качестве предложения: у far2l появился fork с поддержкой lua-макросов, возможно будет интересно добавить сюда сборку этого варианта. Для создания portable-сборки пришлось немного модифицировать скрипты, выложил их сюда: https://github.com/shmuz/far2l/discussions/22

**Comment by unxed** [comment]
Спасибо! Настройки сети добавил в a7247a5fa4147529961fcd3fc2c8bd25593e75a3

Добавить сюда — в смысле в эту же репу положить ваши скрипты? Мне кажется, под них отдельный репозиторий лучше сделать, чтоб от меня не зависеть, если понадобится поправить что-то. Я могу ссылочку поставить у себя потом.

**Comment by sorcodiv** [comment]
Спасибо!
Насчет скриптов - соглашусь. Если попытаться сделать их универсальными, то это может привести к их ненужному усложнению.

**Comment by unxed** [comment]
Кидайте ссылку на свой репозиторий, я добавлю в свой README.

**Comment by sorcodiv** [comment]
Разместил скрипты: https://github.com/sorcodiv/far2lua-build
