### ISSUE TITLE
Problem with umask 077 in portable far (in makeself script)

### ISSUE THREAD

**Issue by sorcodiv** [unxed/far2l-deb#3]
При использовании portable-сборки столкнулся с проблемой выставления прав при копировании файлов: https://github.com/elfmz/far2l/issues/1518
Причина проблемы - выставление umask 077 скриптом makeself.
Предлагаю собирать итоговый архив с опцией --keep-umask:
`makeself/makeself.sh --keep-umask far2l_portable far2l_portable.run far2l ./far2l`

**Comment by unxed** [comment]
Хорошая мысль, сделаете PR в скрипт сборки?

**Comment by sorcodiv** [comment]
Да, постараюсь сделать PR чуть позже, пока руки не дошли - столкнулся с ошибкой сборки, но еще не успел подробнее посмотреть причины.

**Comment by unxed** [comment]
Поправил в https://github.com/unxed/far2l-deb/commit/6555e1dc7000dfced60e5eeaceea46c522b71aeb, проверяйте!

**Comment by sorcodiv** [comment]
Спасибо!
