### ISSUE TITLE
Advice to use in `make_far2l_deb.sh` RAM-folder

### ISSUE THREAD

**Issue by akruphi** [unxed/far2l-deb#5]
For economy SSD & faster compile in `make_far2l_deb.sh` (idea from https://t.me/far2l_ru/10307 ):

lines 8, 9, 10
```
rm -rf far2l
mkdir far2l
cd far2l
```
change to
```
rm -rf far2l
mkdir far2l
sudo mount tmpfs -o size=2G -o uid=`id -u` -o gid=`id -g` -t tmpfs ./far2l
cd far2l
```
and after last line add
```
sudo umount ./far2l
```

**Comment by unxed** [comment]
Thanks!

Is 2G for sure enough? Have you done any measurements?

**Comment by akruphi** [comment]
> Is 2G for sure enough? Have you done any measurements?

Скаченный с гита far2l занимает 100М, build после сборки около 80M.

В телеграмме в совете Вадима было 2Гб. Я так и попробовал. Наверное можно серьёзнее уменьшить до 200-250M. Оперативки у меня хватает и я не стал заморачиваться отлавливать что при компиляции там ещё временного создаётся, особенно, если компилировать с `-j$(nproc --all)`, и подбирать размер.

**Comment by akruphi** [comment]
> Is 2G for sure enough? Have you done any measurements?

После скачивания из git **far2l+jumpword+netcfg+sqlplugin** занимают **126.7M**

Компиляция при `-j$(nproc --all)` (у меня 8 потоков) успешно прошла на монтированном RAM-каталоге размером 200M.

**far2l+jumpword+netcfg+sqlplugin + build** (сборка `-DUSEWX=yes -DCMAKE_BUILD_TYPE=Release` без питона) заняли **196.5M**.

Далее уже для создания deb места не хватило "No space left on device"

На разделе **250M** всё получилось.

Максимально **far2l+jumpword+netcfg+sqlplugin + build + deb** заняли **226.5M**

**Comment by unxed** [comment]
Как насчёт 512 Мб? Покроет потребности с двойным запасом: хватит и на сейчас, и на ближайшее "потом". Мнения?

**Comment by akruphi** [comment]
> Как насчёт 512 Мб? Покроет потребности с двойным запасом: хватит и на сейчас, и на ближайшее "потом". Мнения?

Согласен. Если у кого не взлетит - напишут или сами у себя поправят.

Интересно попробовать бы ещё на разных системах. У меня компилируется похоже через g++. Не может быть такого, что другие компиляторы или версии при работе временных файлов в этом же каталоге создают/удалят, которых при большом кол-ве потоков может стать единомоментно много? Кто с компиляторами дружен и может такое разъяснить?

**Comment by unxed** [comment]
В смысле, не добавлять рамдиск на 512 пока, подождём, что люди скажут?

**Comment by akruphi** [comment]
> В смысле, не добавлять рамдиск на 512 пока, подождём, что люди скажут?

В смысле RAM-каталог использовать уже сейчас. Ну и ждать реакцию, если вдруг пояятся огорченные люди. Скрипт `make_far2l_deb.sh` наверное не особо много людей юзает.

**Comment by VPROFi** [comment]
Вообще, изначально, рам диск я (https://t.me/far2l_ru/10307) использую всегда при компиляции **при разработке** (У меня в фаре, в меню, прописано его создание, cmake и прочие команды) и не только для фар, если нужно 1 раз компилировать скриптом - наверное смысла большого не имеет (если только у вас не hdd). 

и да проверка желательна еще (https://github.com/VPROFi/netcfgplugin#readme), чтобы пароль по sudo каждый раз не вводить.
```sh
BUILD_PATH=/tmp/_build
if ! `mount | grep -q $BUILD_PATH`; then
    mkdir -p $BUILD_PATH
    echo mount tmpfs 2Gb at: $BUILD_PATH
    sudo mount tmpfs -o size=2G -o uid=`id -u` -o gid=`id -g` -t tmpfs $BUILD_PATH
fi
```
unmount естественно не нужен,
```sh
sudo umount ./far2l
```
 **при разработке** частые перекомпиляции только части кода, а не всего и вот для этих перекомпиляций как раз и нужен рам диск.

**Comment by unxed** [comment]
check now pls

**Comment by akruphi** [comment]
Поразбирался с tmpfs - в современном виде она не отбирает сразу назначенную память, а только по мере заполнения раздела файлами отъедает от памяти вплоть до половины всей оперативки, либо до указанного размера (при надобности уходит в своп). Поэтому в скрипте выше можно было не прописывать предельный размер, а использовать по умолчанию = лимит вплоть до половины оперативки.


Для себя я перевел `/tmp` на tmpfs (в Ubuntu это модерново делается через `sudo systemctl enable /usr/share/systemd/tmp.mount` + перезагрузка) и далаю сборку в подкаталоге `/tmp/_build`. В этом случае дополнительного монтирования не надо. Но не все системы по умолчанию держат `/tmp` в tmpfs.

**Comment by unxed** [comment]
Убрать ограничение?
