### ISSUE TITLE
Packages for Ubuntu 16.04

### ISSUE THREAD

**Issue by r44083** [unxed/far2l-deb#8]
Hi, could you please add deb package for Ubuntu 16.04?
As I remember, it was few month ago in your repo.

**Comment by unxed** [comment]
Unfortunately, currently I have no machine available with 16.04 installed to build the packages. Old ones are completely outdated.

Packages for 16.04 are available in the ppa:

https://launchpad.net/~far2l-team/+archive/ubuntu/ppa

>  20181228.d925422~ubuntu16.04.1

**Comment by r44083** [comment]
Thank you.
I download deb package using the link below:
```https://launchpadlibrarian.net/403969130/far2l_20181228.d925422~ubuntu16.04.1_amd64.deb```
