### ISSUE TITLE
far2l_64_tty_18_04.deb don't start in linux mint 18

### ISSUE THREAD

**Issue by sas2job** [unxed/far2l-deb#9]
Running in the terminal gives an error: `far2l: relocation error: far2l: symbol _ZNK8wxWindow7IsShownEv, version WXU_3.0 not defined in file libwx_gtk2u_core-3.0.so.0 with link time reference
`

**Comment by unxed** [comment]
Mint 18 is based on Ubuntu 16.04. Use 16_04 debs.

https://en.wikipedia.org/wiki/Linux_Mint_version_history#Release_history

**Comment by sas2job** [comment]
Thank you. ppa helped install far2l
